
// প্রাকটিস চ্যালেঞ্জ -১:  

// ক্লাস সেভের এর ফাইনাল এক্সাম এ তুমি ফার্স্ট হয়েছ। তোমার বন্ধু আলিয়া, ডালিয়া, সালিয়া, মালিয়া, লিলিয়া আর জ্বালাইয়া - তাদের grade তুমি জানো না। তবে তাদের নম্বর জানো. আলিয়া 95 পেয়েছে, ডালিয়া 66 পেয়েছে, সালিয়া 80 পেয়েছে, মালিয়া পেয়েছে 59, লিলিয়া পেয়েছে 47, জ্বালাইয়া পেয়েছে 77। তুমি JS code দিয়ে তাদের grade বের করে দিতে পারবে?

// ১) যারা ৫০ এর নিচে পেয়েছে, তাদের grade F.

// ২) যারা ৫০ বা তার উপরে পেয়েছে, অথবা ৬০ এর নিচে পেয়েছে, তাদের grade D.

// ৩) যারা ৬০ বা তার উপরে পেয়েছে, অথবা ৭০ এর নিচে পেয়েছে, তাদের grade C.

// ৪) যারা ৭০ বা তার উপরে পেয়েছে, অথবা ৮০ এর নিচে পেয়েছে, তাদের grade B.

// ৫) যারা ৮০ বা তার উপরে পেয়েছে, অথবা ৯০ এর নিচে পেয়েছে, তাদের grade A.

// ৬) যারা ৯০ বা তার উপরে পেয়েছে, তাদের grade A+.



// STUDENTS MARKS





var marksOfAlia = 95
var marksOfDalia = 66
var marksOfSalia = 80
var marksOfMalia = 59
var marksOfLilia = 47
var marksOfJalia = 77


// marksOfAlia
if (marksOfAlia >= 90 ){
    console.log('grade A+')
}
else if(marksOfAlia >= 80 && marksOfAlia < 90){
    console.log('grade A')
}

else if(marksOfAlia >= 70 && marksOfAlia < 80){
    console.log('grade B')
}

else if(marksOfAlia >= 60 && marksOfAlia < 70){
    console.log('grade C')
}

else if(marksOfAlia >= 50 && marksOfAlia < 60){
    console.log('grade D')
}

else if(marksOfAlia < 50 ){
    console.log('grade F')
}
else {
    console.log('purai mara')
}


// marksOfDalia
if (marksOfDalia >= 90 ){
    console.log('grade A+')
}
else if(marksOfDalia >= 80 && marksOfDalia < 90){
    console.log('grade A')
}

else if(marksOfDalia >= 70 && marksOfDalia < 80){
    console.log('grade B')
}

else if(marksOfDalia >= 60 && marksOfDalia < 70){
    console.log('grade C')
}

else if(marksOfDalia >= 50 && marksOfDalia < 60){
    console.log('grade D')
}

else if(marksOfDalia < 50 ){
    console.log('grade F')
}
else {
    console.log('purai mara')
}


// marksOfSalia
if (marksOfSalia >= 90 ){
    console.log('grade A+')
}
else if(marksOfSalia >= 80 && marksOfSalia < 90){
    console.log('grade A')
}

else if(marksOfSalia >= 70 && marksOfSalia < 80){
    console.log('grade B')
}

else if(marksOfSalia >= 60 && marksOfSalia < 70){
    console.log('grade C')
}

else if(marksOfSalia >= 50 && marksOfSalia < 60){
    console.log('grade D')
}

else if(marksOfSalia < 50 ){
    console.log('grade F')
}
else {
    console.log('purai mara')
}


// marksOfMalia
if (marksOfMalia >= 90 ){
    console.log('grade A+')
}
else if(marksOfMalia >= 80 && marksOfMalia < 90){
    console.log('grade A')
}

else if(marksOfMalia >= 70 && marksOfMalia < 80){
    console.log('grade B')
}

else if(marksOfMalia >= 60 && marksOfMalia < 70){
    console.log('grade C')
}

else if(marksOfMalia >= 50 && marksOfMalia < 60){
    console.log('grade D')
}

else if(marksOfMalia < 50 ){
    console.log('grade F')
}
else {
    console.log('purai mara')
}


// marksOfLilia
if (marksOfLilia >= 90 ){
    console.log('grade A+')
}
else if(marksOfLilia >= 80 && marksOfLilia < 90){
    console.log('grade A')
}

else if(marksOfLilia >= 70 && marksOfLilia < 80){
    console.log('grade B')
}

else if(marksOfLilia >= 60 && marksOfLilia < 70){
    console.log('grade C')
}

else if(marksOfLilia >= 50 && marksOfLilia < 60){
    console.log('grade D')
}

else if(marksOfLilia < 50 ){
    console.log('grade F')
}
else {
    console.log('purai mara')
}

// marksOfJalia
if (marksOfJalia>= 90 ){
    console.log('grade A+')
}
else if(marksOfJalia >= 80 && marksOfJalia < 90){
    console.log('grade A')
}

else if(marksOfJalia >= 70 && marksOfJalia < 80){
    console.log('grade B')
}

else if(marksOfJalia >= 60 && marksOfJalia < 70){
    console.log('grade C')
}

else if(marksOfJalia >= 50 && marksOfJalia < 60){
    console.log('grade D')
}

else if(marksOfJalia < 50 ){
    console.log('grade F')
}
else {
    console.log('purai mara')
}